version: '3.4'

services:
  trafficlights.api:
    image: ${DOCKER_REGISTRY-}trafficlightsapi
    build:
      context: .
      dockerfile: TrafficLights.Api/Dockerfile
    links:
      - "trafficlightpostgresdb"
      - "notifications"

  trafficlights.auth:
    image: ${DOCKER_REGISTRY-}trafficlightsauth
    build:     
      context: .     
      dockerfile: TrafficLights.Auth/Dockerfile
    links:
      - "authpostgresdb"

  notifications:
    image: ${DOCKER_REGISTRY-}notifications
    build:     
      context: .     
      dockerfile: Notifications/Dockerfile    

  authpostgresdb:
    image: postgres
    restart: always
    container_name: auth-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgres

  trafficlightpostgresdb:
    image: postgres
    restart: always
    container_name: traffic-light-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: traffic-light
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgres
