version: '3.4'

services:
  trafficlights.api:
    image: ${DOCKER_REGISTRY-}trafficlightsapi
    build:
      context: .
      dockerfile: TrafficLights.Api/Dockerfile
    links:
      - "trafficlightpostgresdb"

  trafficlights.auth:
    image: ${DOCKER_REGISTRY-}trafficlightsauth
    build:     
      context: .     
      dockerfile: TrafficLights.Auth/Dockerfile
    links:
      - "trafficlightpostgresdb"


  trafficlightpostgresdb:
    image: postgres
    restart: always
    container_name: traffic-light-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: traffic-light
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgres


